// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arttzxvdwqaaflaxfxoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFydHR6eHZkd3FhYWZsYXhmeG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTA1ODAsImV4cCI6MjA2NTQ2NjU4MH0.2zmoZ9eIuhYxXtl3uKQApv6pB0W5B3R4WZvCMRkhhbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);